Features/1008 gae mail attachment to gcs
GlobalFishingWatch/gae-mail-attachment-to-gcs pull request #1
Opened 2019-05-14 16:31 UTC by smpiano

Read email attachments a store them in the GCS indicated in the config folder.

Related with> https://github.com/GlobalFishingWatch/GFW-Tasks/issues/1008
Notes> https://docs.google.com/document/d/1ZF4lrxS9A4O4_BcVVMdIokNCsx9kPaPyTWlf8YgH2jc/edit?usp=sharing

2019-05-14 16:48 UTC, andres-arana requested changes
Just some quick changes regarding old code from when we tried the `gsutil cp` approach.

2019-05-14 16:48 UTC, andres-arana commented on config/reception.cfg
> +BOTO_PARALLEL_PROCESS=76
Do you really need the BOTO configuration options here? I thought these are only required for `gsutil`, which we aren't using now.

2019-05-14 16:48 UTC, andres-arana commented on utils/upload_gcs.py
> +        self.boto_process = configParser.get('GCS', 'BOTO_PARALLEL_PROCESS')
Again, these boto settings were required for the `gsutil` approach, which we are not using anymore. Remove this.

2019-05-15 03:13 UTC, enriquetuya requested changes
@smpiano we will start receiving mails from 4 other mail accounts with attachments with the same format and same periodicity (or maybe even more) as Panama.
Let's make sure we have the code to support that.

2019-05-15 14:54 UTC, merged